# Generated by Django 3.1.1 on 2020-09-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('mobile_number', models.CharField(default='', max_length=10)),
                ('department', models.CharField(default='', max_length=10)),
                ('city', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
